name: Publish events to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # ajaa joka päivä klo 06:00 Helsinki-aikaa (noin)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Helsinki
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate artifacts
        env:
          TZ: Europe/Helsinki
        run: |
          python -m src.main --out public
      # index.html pysyy ennallaan, ei ylikirjoiteta


    - name: Deploy to GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4

